### ISSUE TITLE
Usage question: where to put nbverbose dependency for a package

### ISSUE THREAD

**Issue by michaelaye** [muellerzr/nbverbose#4]
Thanks for your package!

I was wondering how to deal with the dependency of the GitHub tests requiring nbverbose for the documentation, but surely somebody just running the package wouldn't require `nbverbose`?
How can I manage this?
Thanks!

**Comment by muellerzr** [comment]
I'm confused on what you mean? Yes the docs workflow requires `nbverbose` but the `main` workflow just requires nbdev?

**Comment by muellerzr** [comment]
You'd put it either explicitly in the pip install of the workflow (see the main workflow) or as a pip extra dependency.

**Comment by michaelaye** [comment]
Ah, the workflow, of course, doh! Still getting used to workflows, sorry!
